//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextApp.EntityFrameworkContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using TextApp.Models;
    public partial class CarsDBEntities : DbContext
    {
        public CarsDBEntities()
            : base("name=CarsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TCars> TCars { get; set; }
        public virtual DbSet<TOrderHistory> TOrderHistory { get; set; }
        public virtual DbSet<TOrders> TOrders { get; set; }
        public virtual DbSet<OrderHistoryView> OrderHistoryView { get; set; }
        public virtual DbSet<OrderView> OrderView { get; set; }
        public virtual DbSet<TClients> TClients { get; set; }
    }
}
